//
//  FBReferencesViewController.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/10/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBReferencesViewControllerInput
{
  func displaySomething(viewModel: FBReferences.Something.ViewModel)
}

protocol FBReferencesViewControllerOutput
{
  func doSomething(request: FBReferences.Something.Request)
}

class FBReferencesViewController: UIViewController, FBReferencesViewControllerInput
{
  var output: FBReferencesViewControllerOutput!
  var router: FBReferencesRouter!
  let contents: [String] = ["Baranzini, Gary. 'TCM Clinic Aid on the App Store.' App Store. N.p., 07 Oct. 2016. Web. 22 Jan. 2017.", "Bensky, Dan, Andrew Gamble, and Ted J. Kaptchuk. Chinese Herbal Medicine: Materia Medica. 3rd ed. Seattle, WA: Eastland, 1993. Print.", "Bensky, Dan, and Randall Barolet. Chinese Herbal Medicine: Formulas & Strategies. Seattle, WA: Eastland, 1990. Print.", "'TCM Wiki.' TCM Wiki. N.p., n.d. Web. 22 Jan. 2017.", "Zhang, Zhongjing, Craig Mitchell, Ye Feng, and Nigel Wiseman. Shang Han Lun = On Cold Damage. Brookline, MA: Paradigm Publications, 1999. Print.", "Zhang, Zhongjing, Nigel Wiseman, and Sabine Wilms. Jin Gui Yao Lue: Translation and Commentaries = Essential Prescriptions of the Golden Cabinet. Taos, NM: Paradigm Publications, 2013. Print."]
  
  
    @IBOutlet weak var tableView: UITableView!
  override func awakeFromNib()
  {
    super.awakeFromNib()
    FBReferencesConfigurator.sharedInstance.configure(viewController: self)
  }
  
  
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    
    tableView.rowHeight = UITableViewAutomaticDimension
    tableView.estimatedRowHeight = 44
    doSomethingOnLoad()
  }
  
  
  
  func doSomethingOnLoad()
  {
    
    
    let request = FBReferences.Something.Request()
    output.doSomething(request: request)
  }
  
  
  
  func displaySomething(viewModel: FBReferences.Something.ViewModel)
  {

  }
}
extension FBReferencesViewController: UITableViewDataSource
{
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return contents.count
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "referenceCell") as! ReferenceCell
        cell.contentLbl.text = contents[indexPath.row]
        return cell
    }
}
class ReferenceCell: UITableViewCell
{
    @IBOutlet weak var contentLbl: UILabel!
    override func awakeFromNib() {
        
    }
}
