//
//  FBReferencesInteractor.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/10/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBReferencesInteractorInput
{
  func doSomething(request: FBReferences.Something.Request)
}

protocol FBReferencesInteractorOutput
{
  func presentSomething(response: FBReferences.Something.Response)
}

class FBReferencesInteractor: FBReferencesInteractorInput
{
  var output: FBReferencesInteractorOutput!
  var worker: FBReferencesWorker!
  
  
  
  func doSomething(request: FBReferences.Something.Request)
  {
    
    
    worker = FBReferencesWorker()
    worker.doSomeWork()
    
    
    
    let response = FBReferences.Something.Response()
    output.presentSomething(response: response)
  }
}
