//
//  FBReferencesConfigurator.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/10/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBReferencesViewController: FBReferencesPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension FBReferencesInteractor: FBReferencesViewControllerOutput
{
}

extension FBReferencesPresenter: FBReferencesInteractorOutput
{
}

class FBReferencesConfigurator
{
  
  
  static let sharedInstance = FBReferencesConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: FBReferencesViewController)
  {
    let router = FBReferencesRouter()
    router.viewController = viewController
    
    let presenter = FBReferencesPresenter()
    presenter.output = viewController
    
    let interactor = FBReferencesInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
