//
//  FBFormulaSearchRouter.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/3/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBFormulaSearchRouterInput
{
    func navigateToProfilePage(profilePageType: ProfileViewType)
}

class FBFormulaSearchRouter: FBFormulaSearchRouterInput
{
  weak var viewController: FBFormulaSearchViewController!
  
  // MARK: - Navigation
  
    func navigateToProfilePage(profilePageType: ProfileViewType)
    {
        if let selectedIndexPath = viewController.tableView.indexPathForSelectedRow {
            if let selectedFormula = viewController.displayedFormulas[selectedIndexPath.row].formulaObj {
                let navigationController = viewController.navigationController
                let profileViewController = profileStoryboard.instantiateViewController(withIdentifier: "FBProfileViewController") as! FBProfileViewController
                profileViewController.profileViewType = profilePageType
                profileViewController.formula = selectedFormula
                navigationController?.pushViewController(profileViewController, animated: true)
            }
        }
    }
  
    // MARK: - Communication

    func passDataToNextScene(segue: UIStoryboardSegue)
    {
        // NOTE: Teach the router which scenes it can communicate with

        if segue.identifier == "ShowSomewhereScene" {
          passDataToSomewhereScene(segue: segue)
        }
    }

    func passDataToSomewhereScene(segue: UIStoryboardSegue)
    {
        // NOTE: Teach the router how to pass data to the next scene

        // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
        // someWhereViewController.output.name = viewController.output.name
    }
}
