//
//  FBFormulaSearchInteractor.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/3/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import FormulaBuilderCore

protocol FBFormulaSearchInteractorInput {
    func fetchFormulas(_ request: FBFormulaSearch.FetchFormulas.Request)
    var formulas: [FBFormula]? { get }
    var homeViewController: FBHomeViewController? { set get }
    var recentSearchViewController: FBRecentSearchesViewController? { set get }
    var herbSearchViewController: FBHerbSearchViewController? { get set }
}

protocol FBFormulaSearchInteractorOutput {
    func presentFetchedFormulas(response: FBFormulaSearch.FetchFormulas.Response)
}

class FBFormulaSearchInteractor: FBFormulaSearchInteractorInput {
    var output: FBFormulaSearchInteractorOutput!
    var formulas: [FBFormula]?
    var homeViewController: FBHomeViewController?
    var recentSearchViewController: FBRecentSearchesViewController?
    var herbSearchViewController: FBHerbSearchViewController?

    func fetchFormulas(_ request: FBFormulaSearch.FetchFormulas.Request) {
        
        store.fetchFormulas(withFilter: .all) { formulas in
            self.formulas = formulas
            let response = FBFormulaSearch.FetchFormulas.Response(formulas: formulas)
            self.output.presentFetchedFormulas(response: response)
        }
    }
}
