//
//  FBFormulaSearchConfigurator.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/3/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBFormulaSearchViewController: FBFormulaSearchPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension FBFormulaSearchInteractor: FBFormulaSearchViewControllerOutput
{
}

extension FBFormulaSearchPresenter: FBFormulaSearchInteractorOutput
{
}

class FBFormulaSearchConfigurator
{
  
  
  static let sharedInstance = FBFormulaSearchConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: FBFormulaSearchViewController)
  {
    let router = FBFormulaSearchRouter()
    router.viewController = viewController
    
    let presenter = FBFormulaSearchPresenter()
    presenter.output = viewController
    
    let interactor = FBFormulaSearchInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
