//
//  FBProfileConfigurator.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/10/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBProfileViewController: FBProfilePresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension FBProfileInteractor: FBProfileViewControllerOutput
{
}

extension FBProfilePresenter: FBProfileInteractorOutput
{
}

class FBProfileConfigurator
{
  
  
  static let sharedInstance = FBProfileConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: FBProfileViewController)
  {
    let router = FBProfileRouter()
    router.viewController = viewController
    
    let presenter = FBProfilePresenter()
    presenter.output = viewController
    
    let interactor = FBProfileInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
