//
//  FBProfileInteractor.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/10/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import FormulaBuilderCore

protocol FBProfileInteractorInput
{
    func saveHerb(request: FBProfile.CreateUpdateHerb.Request, errorCallback: @escaping (_ error: FBStoreError?) -> Void)
    func saveFormula(request: FBProfile.CreateUpdateFormula.Request, errorCallback: @escaping (_ error: FBStoreError?) -> Void)
}

protocol FBProfileInteractorOutput
{
    func presentHerb(response: FBProfile.CreateUpdateHerb.Response)
    func presentFormula(response: FBProfile.CreateUpdateFormula.Response)
}

class FBProfileInteractor: FBProfileInteractorInput
{
    var output: FBProfileInteractorOutput!
    var worker: FBProfileWorker!
    
    func saveHerb(request: FBProfile.CreateUpdateHerb.Request, errorCallback: @escaping (_ error: FBStoreError?) -> Void){
        store.saveHerb(request.saveType, request.herb) { (error) in
            errorCallback(error)
        }
    }
    
    func saveFormula(request: FBProfile.CreateUpdateFormula.Request, errorCallback: @escaping (_ error: FBStoreError?) -> Void) {
        store.saveFormula(request.saveType, request.formula) { (error) in
            errorCallback(error)
        }
    }
}
