//
//  FBProfileModels.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/10/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import FormulaBuilderCore

struct FBProfile
{
    struct CreateUpdateFormula {
        struct Request {
            var formula : FBFormula
            var saveType: SaveType
        }
        
        struct Response {}
        
        struct ViewModel {}
    }
    
    struct CreateUpdateHerb {
        struct Request {
            var herb : FBHerb
            var saveType: SaveType
        }
        
        struct Response {}
        
        struct ViewModel {}
    }
}


