//
//  FBProfilePresenter.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/10/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBProfilePresenterInput
{
    func presentHerb(response: FBProfile.CreateUpdateHerb.Response)
    func presentFormula(response: FBProfile.CreateUpdateFormula.Response)
}

protocol FBProfilePresenterOutput: class
{
    func displayFormulas(viewModel: FBProfile.CreateUpdateFormula.ViewModel)
    func displayHerbs(viewModel: FBProfile.CreateUpdateHerb.ViewModel)
}

class FBProfilePresenter: FBProfilePresenterInput
{
    weak var output: FBProfilePresenterOutput!

    func presentHerb(response: FBProfile.CreateUpdateHerb.Response)
    {
        let viewModel = FBProfile.CreateUpdateHerb.ViewModel()
        output.displayHerbs(viewModel: viewModel)
    }
    
    func presentFormula(response: FBProfile.CreateUpdateFormula.Response)
    {
        let viewModel = FBProfile.CreateUpdateFormula.ViewModel()
        output.displayFormulas(viewModel: viewModel)
    }
}
