//
//  FBSearchResultsViewController.swift
//  FormulaBuilderCS
//
//  Created by YI BIN FENG on 2017-02-28.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBSearchResultsViewControllerInput {
    func displayResults(viewModel: FBSearchResults.Something.ViewModel)
}

protocol FBSearchResultsViewControllerOutput {
  func fetchResults(request: FBSearchResults.Something.Request)
}

class FBSearchResultsViewController: UIViewController {
    var output: FBSearchResultsViewControllerOutput!
    var router: FBSearchResultsRouter!

    override func awakeFromNib() {
        super.awakeFromNib()
        
        FBSearchResultsConfigurator.sharedInstance.configure(viewController: self)
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        
        fetchResults()
    }

    func fetchResults() {

        let request = FBSearchResults.Something.Request()
        output.fetchResults(request: request)
    }

}

// MARK: FBSearchResultsViewControllerInput

extension FBSearchResultsViewController: FBSearchResultsViewControllerInput {
    
    func displayResults(viewModel: FBSearchResults.Something.ViewModel) {
        
    }
    
    
    
}
