//
//  FBSearchResultsInteractor.swift
//  FormulaBuilderCS
//
//  Created by YI BIN FENG on 2017-02-28.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBSearchResultsInteractorInput {
    func fetchResults(request: FBSearchResults.Something.Request)
}

protocol FBSearchResultsInteractorOutput {
    func presentFetchedResults(response: FBSearchResults.Something.Response)
}

class FBSearchResultsInteractor: FBSearchResultsInteractorInput {
    var output: FBSearchResultsInteractorOutput!
    var worker: FBSearchResultsWorker!

    func fetchResults(request: FBSearchResults.Something.Request) {

        worker = FBSearchResultsWorker()
        worker.doSomeWork()

        let response = FBSearchResults.Something.Response()
        output.presentFetchedResults(response: response)
    }
}
