//
//  FBSearchResultsConfigurator.swift
//  FormulaBuilderCS
//
//  Created by YI BIN FENG on 2017-02-28.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBSearchResultsViewController: FBSearchResultsPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension FBSearchResultsInteractor: FBSearchResultsViewControllerOutput
{
}

extension FBSearchResultsPresenter: FBSearchResultsInteractorOutput
{
}

class FBSearchResultsConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = FBSearchResultsConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: FBSearchResultsViewController)
  {
    let router = FBSearchResultsRouter()
    router.viewController = viewController
    
    let presenter = FBSearchResultsPresenter()
    presenter.output = viewController
    
    let interactor = FBSearchResultsInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
