//
//  FBProfileNotesRouter.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/11/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import FormulaBuilderCore

protocol FBProfileNotesRouterInput
{
    func navigateToNoteEditPage()
    func navigateToNoteDetailPage()
}

class FBProfileNotesRouter: FBProfileNotesRouterInput
{
    weak var viewController: FBProfileNotesViewController!
    var note: DisplayedNote?
    // MARK: - Navigation

    func navigateToNoteEditPage() {
        viewController.performSegue(withIdentifier: "NoteToNoteEditSegue", sender: nil)
    }
    
    func navigateToNoteDetailPage() {
        viewController.performSegue(withIdentifier: "NoteToNoteDetailSegue", sender: nil)
    }

    // MARK: - Communication

    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with

        if segue.identifier == "NoteToNoteEditSegue" {
            passDataToProfileNoteEditPage(segue: segue)
        } else if (segue.identifier == "NoteToNoteDetailSegue") {
            passDataToProfileNoteDetailPage(segue: segue)
        }
    }

    func passDataToProfileNoteEditPage(segue: UIStoryboardSegue) {
        let vc: FBProfileNoteEditViewController = segue.destination as! FBProfileNoteEditViewController
        vc.profileMainViewController = viewController.profileMainViewController
    }
    
    func passDataToProfileNoteDetailPage(segue: UIStoryboardSegue) {
        let vc: FBProfileNoteEditViewController = segue.destination as! FBProfileNoteEditViewController
        vc.profileMainViewController = viewController.profileMainViewController
        vc.selectedNote = note!
    }
}
