//
//  FBProfileNotesInteractor.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/11/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBProfileNotesInteractorInput {
    func fetchHerbNotes(request: FBProfileNotes.FetchNotes.Request)
    func fetchFormulaNotes(request: FBProfileNotes.FetchNotes.Request)
}

protocol FBProfileNotesInteractorOutput {
    func presentFetchedNotes(response: FBProfileNotes.FetchNotes.Response)
}

class FBProfileNotesInteractor: FBProfileNotesInteractorInput {
    var output: FBProfileNotesInteractorOutput!
    var worker: FBProfileNotesWorker!
  
    func fetchHerbNotes(request: FBProfileNotes.FetchNotes.Request) {
        store.fetchHerb(withID: request.id) { (herb, error) in
            if (error == nil) {
                self.output.presentFetchedNotes(response: FBProfileNotes.FetchNotes.Response(notes: herb!.notes))
            }
        }
    }
    
    func fetchFormulaNotes(request: FBProfileNotes.FetchNotes.Request) {
        store.fetchFormula(withID: request.id) { (formula, error) in
            if (error == nil) {
                self.output.presentFetchedNotes(response: FBProfileNotes.FetchNotes.Response(notes: formula!.notes))
            }
        }
    }
}
