//
//  FBProfileNotesPresenter.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/11/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBProfileNotesPresenterInput {
    func presentFetchedNotes(response: FBProfileNotes.FetchNotes.Response)
}

protocol FBProfileNotesPresenterOutput: class {
    func displayFetchedNotes(viewModel: FBProfileNotes.FetchNotes.ViewModel)
}

class FBProfileNotesPresenter: FBProfileNotesPresenterInput {
    weak var output: FBProfileNotesPresenterOutput!
    
    func presentFetchedNotes(response: FBProfileNotes.FetchNotes.Response) {
        let notes = response.notes
        var displayedNotes : [DisplayedNote] = [DisplayedNote]()
        
        notes.forEach { (note) in
            displayedNotes.append(DisplayedNote(with: note))
        }
        
        output.displayFetchedNotes(viewModel: FBProfileNotes.FetchNotes.ViewModel(displayedNotes: displayedNotes))
    }
}
