//
//  FBAddToFormulaRouter.swift
//  FormulaBuilderCS
//
//  Created by YI BIN FENG on 2017-02-27.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBAddToFormulaRouterInput
{
  func navigateToProfilePage(with herbID: String)
}

class FBAddToFormulaRouter: FBAddToFormulaRouterInput
{
  weak var viewController: FBAddToFormulaViewController!
  
    func navigateToProfilePage(with herbID: String)
    {
        store.fetchHerb(withID: herbID) { herb, error in
            
            let navigationController = self.viewController.navigationController
            let profileViewController = profileStoryboard.instantiateViewController(withIdentifier: "FBProfileViewController") as! FBProfileViewController
            profileViewController.herb = herb
            navigationController?.pushViewController(profileViewController, animated: true)
        }
    }
  
  func passDataToNextScene(segue: UIStoryboardSegue)
  {
    // NOTE: Teach the router which scenes it can communicate with
    
    if segue.identifier == "ShowSomewhereScene" {
      passDataToSomewhereScene(segue: segue)
    }
  }
  
  func passDataToSomewhereScene(segue: UIStoryboardSegue)
  {
    // NOTE: Teach the router how to pass data to the next scene
    
    // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
    // someWhereViewController.output.name = viewController.output.name
  }
}
