//
//  FBAddToFormulaConfigurator.swift
//  FormulaBuilderCS
//
//  Created by YI BIN FENG on 2017-02-27.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBAddToFormulaViewController: FBAddToFormulaPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension FBAddToFormulaInteractor: FBAddToFormulaViewControllerOutput
{
}

extension FBAddToFormulaPresenter: FBAddToFormulaInteractorOutput
{
}

class FBAddToFormulaConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = FBAddToFormulaConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: FBAddToFormulaViewController)
  {
    let router = FBAddToFormulaRouter()
    router.viewController = viewController
    
    let presenter = FBAddToFormulaPresenter()
    presenter.output = viewController
    
    let interactor = FBAddToFormulaInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
