//
//  FBHerbSearchConfigurator.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/3/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBHerbSearchViewController: FBHerbSearchPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension FBHerbSearchInteractor: FBHerbSearchViewControllerOutput {}

extension FBHerbSearchPresenter: FBHerbSearchInteractorOutput {}

class FBHerbSearchConfigurator {

    static let sharedInstance = FBHerbSearchConfigurator()
  
    private init() {}

    func configure(viewController: FBHerbSearchViewController) {
        let router = FBHerbSearchRouter()
        router.viewController = viewController

        let presenter = FBHerbSearchPresenter()
        presenter.output = viewController

        let interactor = FBHerbSearchInteractor()
        interactor.output = presenter

        viewController.output = interactor
        viewController.router = router
        
    }
}
