//
//  FBChannelsConfigurator.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/20/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBChannelsViewController: FBChannelsPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension FBChannelsInteractor: FBChannelsViewControllerOutput
{
}

extension FBChannelsPresenter: FBChannelsInteractorOutput
{
}

class FBChannelsConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = FBChannelsConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: FBChannelsViewController)
  {
    let router = FBChannelsRouter()
    router.viewController = viewController
    
    let presenter = FBChannelsPresenter()
    presenter.output = viewController
    
    let interactor = FBChannelsInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
