//
//  FBChannelsModels.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/20/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import FormulaBuilderCore

struct FBChannels
{
    struct FetchChannels
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
            var displayedChannels: [FBChannel]
        }
    }
}
