//
//  FBChannelsPresenter.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/20/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBChannelsPresenterInput
{
    func presentFetchedChannels(response: FBChannels.FetchChannels.Response)
}

protocol FBChannelsPresenterOutput: class
{
    func displayFetchedChannels(viewModel: FBChannels.FetchChannels.ViewModel)
}

class FBChannelsPresenter: FBChannelsPresenterInput
{
    weak var output: FBChannelsPresenterOutput!
    
    
    func presentFetchedChannels(response: FBChannels.FetchChannels.Response) {
        
        store.allChannels { channels in
            let viewModel = FBChannels.FetchChannels.ViewModel(displayedChannels: channels)
            self.output.displayFetchedChannels(viewModel: viewModel)
        }
    }
}
