//
//  FBChannelsInteractor.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/20/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBChannelsInteractorInput
{
    func fetchChannels(request: FBChannels.FetchChannels.Request)
    var advancedSearchViewController: FBAdvancedSearchViewController? { get set }
    var profileViewController: FBProfileViewController? {get set}
}

protocol FBChannelsInteractorOutput
{
    func presentFetchedChannels(response: FBChannels.FetchChannels.Response)
}

class FBChannelsInteractor: FBChannelsInteractorInput
{
    var output: FBChannelsInteractorOutput!
    var worker: FBChannelsWorker!
    var advancedSearchViewController: FBAdvancedSearchViewController?
    var profileViewController: FBProfileViewController?
    
    func fetchChannels(request: FBChannels.FetchChannels.Request)
    {
        
        worker = FBChannelsWorker()
        worker.doSomeWork()
        
        let response = FBChannels.FetchChannels.Response()
        output.presentFetchedChannels(response: response)
    }
}
