//
//  FBProfileMoreModels.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/11/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import FormulaBuilderCore

struct FBProfileMore
{
  struct Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}

class DisplayPreparation: NSObject {
    var id : String? = nil
    var name = ""
    var content = ""
    var isSelected = false
    var preparationObj : FBPreparation? = nil
    init(with preparation: FBPreparation) {
        if let preparationId = preparation.id
        {
            id = preparationId
        }
        name = preparation.name!
        content = preparation.content!
    }
    override init()
    {
        
    }
}
