//
//  FBProfileMorePresenter.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/11/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBProfileMorePresenterInput
{
  func presentSomething(response: FBProfileMore.Something.Response)
}

protocol FBProfileMorePresenterOutput: class
{
  func displaySomething(viewModel: FBProfileMore.Something.ViewModel)
}

class FBProfileMorePresenter: FBProfileMorePresenterInput
{
  weak var output: FBProfileMorePresenterOutput!
  
  
  
  func presentSomething(response: FBProfileMore.Something.Response)
  {
    
    
    let viewModel = FBProfileMore.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
