//
//  FBProfileMoreConfigurator.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/11/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBProfileMoreViewController: FBProfileMorePresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension FBProfileMoreInteractor: FBProfileMoreViewControllerOutput
{
}

extension FBProfileMorePresenter: FBProfileMoreInteractorOutput
{
}

class FBProfileMoreConfigurator
{
  
  
  static let sharedInstance = FBProfileMoreConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: FBProfileMoreViewController)
  {
    let router = FBProfileMoreRouter()
    router.viewController = viewController
    
    let presenter = FBProfileMorePresenter()
    presenter.output = viewController
    
    let interactor = FBProfileMoreInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
