//
//  FBProfileTextsPresenter.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/11/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBProfileTextsPresenterInput {
    func presentSomething(response: FBProfileTexts.Something.Response)
}

protocol FBProfileTextsPresenterOutput: class {
    func displaySomething(viewModel: FBProfileTexts.Something.ViewModel)
}

class FBProfileTextsPresenter: FBProfileTextsPresenterInput
{
    weak var output: FBProfileTextsPresenterOutput!
    
    func presentSomething(response: FBProfileTexts.Something.Response) {
        let viewModel = FBProfileTexts.Something.ViewModel()
        output.displaySomething(viewModel: viewModel)
    }
}
