//
//  FBProfileTextsInteractor.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/11/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBProfileTextsInteractorInput {
  func doSomething(request: FBProfileTexts.Something.Request)
}

protocol FBProfileTextsInteractorOutput {
    func presentSomething(response: FBProfileTexts.Something.Response)
}

class FBProfileTextsInteractor: FBProfileTextsInteractorInput {
    var output: FBProfileTextsInteractorOutput!
    var worker: FBProfileTextsWorker!

    func doSomething(request: FBProfileTexts.Something.Request) {
        worker = FBProfileTextsWorker()
        worker.doSomeWork()

        let response = FBProfileTexts.Something.Response()
        output.presentSomething(response: response)
    }
}
