//
//  FBProfileTextsConfigurator.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/11/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBProfileTextsViewController: FBProfileTextsPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension FBProfileTextsInteractor: FBProfileTextsViewControllerOutput
{
}

extension FBProfileTextsPresenter: FBProfileTextsInteractorOutput
{
}

class FBProfileTextsConfigurator
{
  
  
  static let sharedInstance = FBProfileTextsConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: FBProfileTextsViewController)
  {
    let router = FBProfileTextsRouter()
    router.viewController = viewController
    
    let presenter = FBProfileTextsPresenter()
    presenter.output = viewController
    
    let interactor = FBProfileTextsInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
