//
//  FBCategoriesListConfigurator.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/10/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBCategoriesListViewController: FBCategoriesListPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension FBCategoriesListInteractor: FBCategoriesListViewControllerOutput
{
}

extension FBCategoriesListPresenter: FBCategoriesListInteractorOutput
{
}

class FBCategoriesListConfigurator
{
  
  
  static let sharedInstance = FBCategoriesListConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: FBCategoriesListViewController)
  {
    let router = FBCategoriesListRouter()
    router.viewController = viewController
    
    let presenter = FBCategoriesListPresenter()
    presenter.output = viewController
    
    let interactor = FBCategoriesListInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
