//
//  FBProfileInfoConfigurator.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/11/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBProfileInfoViewController: FBProfileInfoPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension FBProfileInfoInteractor: FBProfileInfoViewControllerOutput {
    
}

extension FBProfileInfoPresenter: FBProfileInfoInteractorOutput {
    
}

class FBProfileInfoConfigurator {
  
    static let sharedInstance = FBProfileInfoConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: FBProfileInfoViewController) {
        let router = FBProfileInfoRouter()
        router.viewController = viewController

        let presenter = FBProfileInfoPresenter()
        presenter.output = viewController

        let interactor = FBProfileInfoInteractor()
        interactor.output = presenter

        viewController.output = interactor
        viewController.router = router
    }
}
