//
//  FBProfileNoteEditRouter.swift
//  FormulaBuilderCS
//
//  Created by a on 2/19/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBProfileNoteEditRouterInput
{
    func navigateToSomewhere()
}

class FBProfileNoteEditRouter: FBProfileNoteEditRouterInput
{
    weak var viewController: FBProfileNoteEditViewController!

    // MARK: - Navigation
    func navigateToSomewhere() {

    }

    // MARK: - Communication
    func passDataToNextScene(segue: UIStoryboardSegue) {
        if segue.identifier == "ShowSomewhereScene" {
            passDataToSomewhereScene(segue: segue)
        }
    }

    func passDataToSomewhereScene(segue: UIStoryboardSegue) {

    }
}
