//
//  FBProfileNoteEditConfigurator.swift
//  FormulaBuilderCS
//
//  Created by a on 2/19/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBProfileNoteEditViewController: FBProfileNoteEditPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension FBProfileNoteEditInteractor: FBProfileNoteEditViewControllerOutput {}
extension FBProfileNoteEditPresenter: FBProfileNoteEditInteractorOutput {}

class FBProfileNoteEditConfigurator {
    // MARK: - Object lifecycle
    static let sharedInstance = FBProfileNoteEditConfigurator()
  
    private init() {}
  
    // MARK: - Configuration
    func configure(viewController: FBProfileNoteEditViewController)
    {
        let router = FBProfileNoteEditRouter()
        router.viewController = viewController

        let presenter = FBProfileNoteEditPresenter()
        presenter.output = viewController

        let interactor = FBProfileNoteEditInteractor()
        interactor.output = presenter

        viewController.output = interactor
        viewController.router = router
    }
}
