//
//  FBProfileNoteEditModels.swift
//  FormulaBuilderCS
//
//  Created by a on 2/19/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import FormulaBuilderCore

struct FBProfileNoteEdit
{
    struct AddNote {
        
        struct Request {
            var note: FBNote
            var toType: ToType
            var toID: String
        }
        
        struct Response {}
        
        struct ViewModel {}
    }
    
    struct UpdateNote {
        
        struct Request {
            var note: FBNote
        }
        
        struct Response {}
        
        struct ViewModel {}
    }
}
