//
//  FBProfileNoteEditPresenter.swift
//  FormulaBuilderCS
//
//  Created by a on 2/19/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBProfileNoteEditPresenterInput {
  func presentSomething(response: FBProfileNoteEdit.AddNote.Response)
}

protocol FBProfileNoteEditPresenterOutput: class {
  func displaySomething(viewModel: FBProfileNoteEdit.AddNote.ViewModel)
}

class FBProfileNoteEditPresenter: FBProfileNoteEditPresenterInput {
    weak var output: FBProfileNoteEditPresenterOutput!

    func presentSomething(response: FBProfileNoteEdit.AddNote.Response) {
        let viewModel = FBProfileNoteEdit.AddNote.ViewModel()
        output.displaySomething(viewModel: viewModel)
    }
}
