//
//  FBHistoryPresenter.swift
//  FormulaBuilderCS
//
//  Created by YI BIN FENG on 2017-02-28.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBHistoryPresenterInput
{
  func presentSomething(response: FBHistory.Something.Response)
}

protocol FBHistoryPresenterOutput: class
{
  func displaySomething(viewModel: FBHistory.Something.ViewModel)
}

class FBHistoryPresenter: FBHistoryPresenterInput
{
  weak var output: FBHistoryPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: FBHistory.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = FBHistory.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
