//
//  FBHistoryInteractor.swift
//  FormulaBuilderCS
//
//  Created by YI BIN FENG on 2017-02-28.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBHistoryInteractorInput
{
  func doSomething(request: FBHistory.Something.Request)
}

protocol FBHistoryInteractorOutput
{
  func presentSomething(response: FBHistory.Something.Response)
}

class FBHistoryInteractor: FBHistoryInteractorInput
{
  var output: FBHistoryInteractorOutput!
  var worker: FBHistoryWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: FBHistory.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = FBHistoryWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = FBHistory.Something.Response()
    output.presentSomething(response: response)
  }
}
