//
//  FBMenuInteractor.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/3/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBMenuInteractorInput
{
  func doSomething(request: FBMenu.Something.Request)
}

protocol FBMenuInteractorOutput
{
  func presentSomething(response: FBMenu.Something.Response)
}

class FBMenuInteractor: FBMenuInteractorInput
{
  var output: FBMenuInteractorOutput!
  var worker: FBMenuWorker!
  
  
  
  func doSomething(request: FBMenu.Something.Request)
  {
    
    
    worker = FBMenuWorker()
    worker.doSomeWork()
    
    
    
    let response = FBMenu.Something.Response()
    output.presentSomething(response: response)
  }
}
