//
//  FBMenuPresenter.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/3/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBMenuPresenterInput
{
  func presentSomething(response: FBMenu.Something.Response)
}

protocol FBMenuPresenterOutput: class
{
  func displaySomething(viewModel: FBMenu.Something.ViewModel)
}

class FBMenuPresenter: FBMenuPresenterInput
{
  weak var output: FBMenuPresenterOutput!
  
  
  
  func presentSomething(response: FBMenu.Something.Response)
  {
    
    
    let viewModel = FBMenu.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
