//
//  FBRecentSearchesInteractor.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/10/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBRecentSearchesInteractorInput
{
  func doSomething(request: FBRecentSearches.Something.Request)
}

protocol FBRecentSearchesInteractorOutput
{
  func presentSomething(response: FBRecentSearches.Something.Response)
}

class FBRecentSearchesInteractor: FBRecentSearchesInteractorInput
{
    var output: FBRecentSearchesInteractorOutput!
    var worker: FBRecentSearchesWorker!
    var herbSearchViewController: FBHerbSearchViewController!
    var formulaSearchViewController: FBFormulaSearchViewController!

    func doSomething(request: FBRecentSearches.Something.Request)
    {
        worker = FBRecentSearchesWorker()
        worker.doSomeWork()

        let response = FBRecentSearches.Something.Response()
        output.presentSomething(response: response)
    }
}
