//
//  FBRecentSearchesConfigurator.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/10/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBRecentSearchesViewController: FBRecentSearchesPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension FBRecentSearchesInteractor: FBRecentSearchesViewControllerOutput
{
}

extension FBRecentSearchesPresenter: FBRecentSearchesInteractorOutput
{
}

class FBRecentSearchesConfigurator
{
  
  
  static let sharedInstance = FBRecentSearchesConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: FBRecentSearchesViewController)
  {
    let router = FBRecentSearchesRouter()
    router.viewController = viewController
    
    let presenter = FBRecentSearchesPresenter()
    presenter.output = viewController
    
    let interactor = FBRecentSearchesInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
