//
//  FBLanguagesInteractor.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/16/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBLanguagesInteractorInput {
    func doSomething(request: FBLanguages.Something.Request)
    var languages: [String] { set get }
}

protocol FBLanguagesInteractorOutput
{
  func presentSomething(response: FBLanguages.Something.Response)
}

class FBLanguagesInteractor: FBLanguagesInteractorInput
{
  var output: FBLanguagesInteractorOutput!
  var worker: FBLanguagesWorker!
    
    var languages = ["English", "Chinese"]
  
  // MARK: - Business logic
  
  func doSomething(request: FBLanguages.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = FBLanguagesWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = FBLanguages.Something.Response()
    output.presentSomething(response: response)
  }
}
