//
//  FBLanguagesConfigurator.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/16/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBLanguagesViewController: FBLanguagesPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension FBLanguagesInteractor: FBLanguagesViewControllerOutput
{
}

extension FBLanguagesPresenter: FBLanguagesInteractorOutput
{
}

class FBLanguagesConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = FBLanguagesConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: FBLanguagesViewController)
  {
    let router = FBLanguagesRouter()
    router.viewController = viewController
    
    let presenter = FBLanguagesPresenter()
    presenter.output = viewController
    
    let interactor = FBLanguagesInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
