//
//  FBLanguagesPresenter.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/16/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBLanguagesPresenterInput
{
  func presentSomething(response: FBLanguages.Something.Response)
}

protocol FBLanguagesPresenterOutput: class
{
  func displaySomething(viewModel: FBLanguages.Something.ViewModel)
}

class FBLanguagesPresenter: FBLanguagesPresenterInput
{
  weak var output: FBLanguagesPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: FBLanguages.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = FBLanguages.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
