//
//  FBDisplayOptionsPresenter.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/16/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBDisplayOptionsPresenterInput
{
  func presentSomething(response: FBDisplayOptions.Something.Response)
}

protocol FBDisplayOptionsPresenterOutput: class
{
  func displaySomething(viewModel: FBDisplayOptions.Something.ViewModel)
}

class FBDisplayOptionsPresenter: FBDisplayOptionsPresenterInput
{
  weak var output: FBDisplayOptionsPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: FBDisplayOptions.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = FBDisplayOptions.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
