//
//  FBAddNewLanguageConfigurator.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/17/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBAddNewLanguageViewController: FBAddNewLanguagePresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension FBAddNewLanguageInteractor: FBAddNewLanguageViewControllerOutput
{
}

extension FBAddNewLanguagePresenter: FBAddNewLanguageInteractorOutput
{
}

class FBAddNewLanguageConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = FBAddNewLanguageConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: FBAddNewLanguageViewController)
  {
    let router = FBAddNewLanguageRouter()
    router.viewController = viewController
    
    let presenter = FBAddNewLanguagePresenter()
    presenter.output = viewController
    
    let interactor = FBAddNewLanguageInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
