//
//  FBAddNewLanguageViewController.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/17/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBAddNewLanguageViewControllerInput
{
  func displaySomething(viewModel: FBAddNewLanguage.Something.ViewModel)
}

protocol FBAddNewLanguageViewControllerOutput {

    func selectedLanguage(_ language: String)
}

class FBAddNewLanguageViewController: UITableViewController, FBAddNewLanguageViewControllerInput
{
  var output: FBAddNewLanguageViewControllerOutput!
  var router: FBAddNewLanguageRouter!
    
    var languages = ["Arabic", "Bengali", "Bulgarian", "Catalan", "Estonian", "Finnish", "Flemish", "French", "Greek", "Hinglish", "Italian", "Japanese", "Korean", "Latvian", "Russian", "Slovak"]
  
  // MARK: - Object lifecycle
  
  override func awakeFromNib()
  {
    super.awakeFromNib()
    FBAddNewLanguageConfigurator.sharedInstance.configure(viewController: self)
  }
  
  // MARK: - View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomethingOnLoad()
  }
  
  // MARK: - Event handling
  
  func doSomethingOnLoad()
  {

  }
  
  // MARK: - Display logic
  
  func displaySomething(viewModel: FBAddNewLanguage.Something.ViewModel)
  {
    // NOTE: Display the result from the Presenter
    
    // nameTextField.text = viewModel.name
  }
    
    // MARK: UITableViewDataSource
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return languages.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        var cell = tableView.dequeueReusableCell(withIdentifier: "cell")
        if cell == nil {
            cell = UITableViewCell.init(style: .default, reuseIdentifier: "cell")
            cell?.textLabel?.font = FBFont.SFUIText_Regalur17()
            cell?.textLabel?.textColor = FBColor.hexColor_030303()
        }
        
        cell?.textLabel?.text = languages[indexPath.row]
        
        return cell!
    }
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let language = languages[indexPath.row]
        
        output.selectedLanguage(language)
    }
    
}






