//
//  FBHomeRouter.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/3/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBHomeRouterInput {
    func navigateToSomewhere()
}

class FBHomeRouter: FBHomeRouterInput {
    weak var viewController: FBHomeViewController!
    var formulaSearchViewController: FBFormulaSearchViewController!
    var herbSearchViewController: FBHerbSearchViewController!
  
  // MARK: - Navigation
  
    func navigateToSomewhere() {
    // NOTE: Teach the router how to navigate to another scene. Some examples follow:
    
    // 1. Trigger a storyboard segue
    // viewController.performSegueWithIdentifier("ShowSomewhereScene", sender: nil)
    
    // 2. Present another view controller programmatically
    // viewController.presentViewController(someWhereViewController, animated: true, completion: nil)
    
    // 3. Ask the navigation controller to push another view controller onto the stack
    // viewController.navigationController?.pushViewController(someWhereViewController, animated: true)
    
    // 4. Present a view controller from a different storyboard
    // let storyboard = UIStoryboard(name: "OtherThanMain", bundle: nil)
    // let someWhereViewController = storyboard.instantiateInitialViewController() as! SomeWhereViewController
    // viewController.navigationController?.pushViewController(someWhereViewController, animated: true)
  }
  
  // MARK: - Communication
  
    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
        if segue.identifier == "HerbSearchViewController" {
            herbSearchViewController = segue.destination as! FBHerbSearchViewController
            
            viewController.output.herbSearchViewController = herbSearchViewController
            herbSearchViewController.output.homeViewController = viewController
            
        } else if segue.identifier == "FormulaSearchViewController" {
            formulaSearchViewController = segue.destination as! FBFormulaSearchViewController
            
            viewController.output.formulaSearchViewController = formulaSearchViewController
            herbSearchViewController.output.formulaSearchViewController = formulaSearchViewController
            
            formulaSearchViewController.output.herbSearchViewController = herbSearchViewController
            formulaSearchViewController.output.homeViewController = viewController
        }
    }
  
    func passDataToSomewhereScene(segue: UIStoryboardSegue) {

    }
}
