//
//  FBHomePresenter.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/3/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBHomePresenterInput {
    func presentSomething(response: FBHome.Something.Response)
}

protocol FBHomePresenterOutput: class {

}

class FBHomePresenter: FBHomePresenterInput {
    weak var output: FBHomePresenterOutput!
    func presentSomething(response: FBHome.Something.Response) {}
}
