//
//  FBHomeInteractor.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/3/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import FormulaBuilderCore

protocol FBHomeInteractorInput {
    var herbSearchViewController: FBHerbSearchViewController! { get set }
    var formulaSearchViewController: FBFormulaSearchViewController! { get set }
}

protocol FBHomeInteractorOutput {
    func presentSomething(response: FBHome.Something.Response)
}

class FBHomeInteractor: FBHomeInteractorInput {
    var output: FBHomeInteractorOutput!
    var worker: FBHomeWorker!
    var herbSearchViewController: FBHerbSearchViewController!
    var formulaSearchViewController: FBFormulaSearchViewController!
}
