//
//  FBReportBugsInteractor.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/7/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBReportBugsInteractorInput
{
  func doSomething(request: FBReportBugs.Something.Request)
}

protocol FBReportBugsInteractorOutput
{
  func presentSomething(response: FBReportBugs.Something.Response)
}

class FBReportBugsInteractor: FBReportBugsInteractorInput
{
  var output: FBReportBugsInteractorOutput!
  var worker: FBReportBugsWorker!
  
  
  
  func doSomething(request: FBReportBugs.Something.Request)
  {
    
    
    worker = FBReportBugsWorker()
    worker.doSomeWork()
    
    
    
    let response = FBReportBugs.Something.Response()
    output.presentSomething(response: response)
  }
}
