//
//  FBReportBugsPresenter.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/7/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBReportBugsPresenterInput
{
  func presentSomething(response: FBReportBugs.Something.Response)
}

protocol FBReportBugsPresenterOutput: class
{
  func displaySomething(viewModel: FBReportBugs.Something.ViewModel)
}

class FBReportBugsPresenter: FBReportBugsPresenterInput
{
  weak var output: FBReportBugsPresenterOutput!
  
  
  
  func presentSomething(response: FBReportBugs.Something.Response)
  {
    
    
    let viewModel = FBReportBugs.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
