//
//  FBReportBugsConfigurator.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/7/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBReportBugsViewController: FBReportBugsPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension FBReportBugsInteractor: FBReportBugsViewControllerOutput
{
}

extension FBReportBugsPresenter: FBReportBugsInteractorOutput
{
}

class FBReportBugsConfigurator
{
  
  
  static let sharedInstance = FBReportBugsConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: FBReportBugsViewController)
  {
    let router = FBReportBugsRouter()
    router.viewController = viewController
    
    let presenter = FBReportBugsPresenter()
    presenter.output = viewController
    
    let interactor = FBReportBugsInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
