//
//  FBReportBugsViewController.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/7/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBReportBugsViewControllerInput
{
  func displaySomething(viewModel: FBReportBugs.Something.ViewModel)
}

protocol FBReportBugsViewControllerOutput
{
  func doSomething(request: FBReportBugs.Something.Request)
}

class FBReportBugsViewController: UIViewController, FBReportBugsViewControllerInput
{
  var output: FBReportBugsViewControllerOutput!
  var router: FBReportBugsRouter!
  
    @IBOutlet weak var textView: UITextView!
  
  
  override func awakeFromNib()
  {
    super.awakeFromNib()
    FBReportBugsConfigurator.sharedInstance.configure(viewController: self)
  }
  
  
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomethingOnLoad()
  }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        textView.becomeFirstResponder()
    }
  
  
  
  func doSomethingOnLoad()
  {
    
    
    let request = FBReportBugs.Something.Request()
    output.doSomething(request: request)
  }
  
  
  
  func displaySomething(viewModel: FBReportBugs.Something.ViewModel)
  {

  }
    

    
    
    
    
    
    
    
    
    
}
