//
//  FBSettingsPresenter.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/10/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBSettingsPresenterInput
{
  func presentSomething(response: FBSettings.Something.Response)
}

protocol FBSettingsPresenterOutput: class
{
  func displaySomething(viewModel: FBSettings.Something.ViewModel)
}

class FBSettingsPresenter: FBSettingsPresenterInput
{
  weak var output: FBSettingsPresenterOutput!
  
  
  
  func presentSomething(response: FBSettings.Something.Response)
  {
    
    
    let viewModel = FBSettings.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
