//
//  FBSettingsConfigurator.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/10/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBSettingsViewController: FBSettingsPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension FBSettingsInteractor: FBSettingsViewControllerOutput
{
}

extension FBSettingsPresenter: FBSettingsInteractorOutput
{
}

class FBSettingsConfigurator
{
  
  
  static let sharedInstance = FBSettingsConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: FBSettingsViewController)
  {
    let router = FBSettingsRouter()
    router.viewController = viewController
    
    let presenter = FBSettingsPresenter()
    presenter.output = viewController
    
    let interactor = FBSettingsInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
