//
//  FBAdvancedSearchPresenter.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/10/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBAdvancedSearchPresenterInput
{
  func presentSomething(response: FBAdvancedSearch.Something.Response)
}

protocol FBAdvancedSearchPresenterOutput: class
{
  func displaySomething(viewModel: FBAdvancedSearch.Something.ViewModel)
}

class FBAdvancedSearchPresenter: FBAdvancedSearchPresenterInput
{
  weak var output: FBAdvancedSearchPresenterOutput!
  
  
  
  func presentSomething(response: FBAdvancedSearch.Something.Response)
  {
    
    
    let viewModel = FBAdvancedSearch.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
