//
//  FBAdvancedSearchRouter.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/10/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBAdvancedSearchRouterInput {
    func navigateToSomewhere()
}

class FBAdvancedSearchRouter: FBAdvancedSearchRouterInput {
    weak var viewController: FBAdvancedSearchViewController!
    
    func navigateToSomewhere() {}
    
    func passDataToNextScene(segue: UIStoryboardSegue) {
        
        if segue.identifier == "Channels" {
            
            viewController.output.channelsViewController = segue.destination as! FBChannelsViewController
            (segue.destination as! FBChannelsViewController).output.advancedSearchViewController = viewController
        }
    }
}
