//
//  FBAdvancedSearchInteractor.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/10/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBAdvancedSearchInteractorInput
{
    func doSomething(request: FBAdvancedSearch.Something.Request)
    var channelsViewController: FBChannelsViewController! { get set }
}

protocol FBAdvancedSearchInteractorOutput
{
    func presentSomething(response: FBAdvancedSearch.Something.Response)
}

class FBAdvancedSearchInteractor: FBAdvancedSearchInteractorInput
{
    var output: FBAdvancedSearchInteractorOutput!
    var worker: FBAdvancedSearchWorker!
    var channelsViewController: FBChannelsViewController!
    
    func doSomething(request: FBAdvancedSearch.Something.Request)
    {
        
        worker = FBAdvancedSearchWorker()
        worker.doSomeWork()
        
        let response = FBAdvancedSearch.Something.Response()
        output.presentSomething(response: response)
    }
}
