//
//  FBAdvancedSearchConfigurator.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/10/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBAdvancedSearchViewController: FBAdvancedSearchPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension FBAdvancedSearchInteractor: FBAdvancedSearchViewControllerOutput
{
}

extension FBAdvancedSearchPresenter: FBAdvancedSearchInteractorOutput
{
}

class FBAdvancedSearchConfigurator
{
  
  
  static let sharedInstance = FBAdvancedSearchConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: FBAdvancedSearchViewController)
  {
    let router = FBAdvancedSearchRouter()
    router.viewController = viewController
    
    let presenter = FBAdvancedSearchPresenter()
    presenter.output = viewController
    
    let interactor = FBAdvancedSearchInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
