//
//  FBRequestContentInteractor.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/7/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBRequestContentInteractorInput
{
  func doSomething(request: FBRequestContent.Something.Request)
}

protocol FBRequestContentInteractorOutput
{
  func presentSomething(response: FBRequestContent.Something.Response)
}

class FBRequestContentInteractor: FBRequestContentInteractorInput
{
  var output: FBRequestContentInteractorOutput!
  var worker: FBRequestContentWorker!
  
  
  
  func doSomething(request: FBRequestContent.Something.Request)
  {
    
    
    worker = FBRequestContentWorker()
    worker.doSomeWork()
    
    
    
    let response = FBRequestContent.Something.Response()
    output.presentSomething(response: response)
  }
}
