//
//  FBRequestContentViewController.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/7/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBRequestContentViewControllerInput
{
  func displaySomething(viewModel: FBRequestContent.Something.ViewModel)
}

protocol FBRequestContentViewControllerOutput
{
  func doSomething(request: FBRequestContent.Something.Request)
}

class FBRequestContentViewController: UIViewController, FBRequestContentViewControllerInput
{
  var output: FBRequestContentViewControllerOutput!
  var router: FBRequestContentRouter!
  
  @IBOutlet weak var textView: UITextView!
  
  override func awakeFromNib()
  {
    super.awakeFromNib()
    FBRequestContentConfigurator.sharedInstance.configure(viewController: self)
  }
  
  
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomethingOnLoad()
  }
  
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        textView.becomeFirstResponder()
    }
  
  func doSomethingOnLoad()
  {
    
    
    let request = FBRequestContent.Something.Request()
    output.doSomething(request: request)
  }
  
  
  
  func displaySomething(viewModel: FBRequestContent.Something.ViewModel)
  {

  }
    
    
    

    
    
    
    

    
    
}
