//
//  FBRequestContentPresenter.swift
//  FormulaBuilderCS
//
//  Created by PFIdev on 2/7/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBRequestContentPresenterInput
{
  func presentSomething(response: FBRequestContent.Something.Response)
}

protocol FBRequestContentPresenterOutput: class
{
  func displaySomething(viewModel: FBRequestContent.Something.ViewModel)
}

class FBRequestContentPresenter: FBRequestContentPresenterInput
{
  weak var output: FBRequestContentPresenterOutput!
  
  
  
  func presentSomething(response: FBRequestContent.Something.Response)
  {
    
    
    let viewModel = FBRequestContent.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
