//
//  FBProfileFormulasConfigurator.swift
//  FormulaBuilderCS
//
//  Created by a on 2/19/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension FBProfileFormulasViewController: FBProfileFormulasPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension FBProfileFormulasInteractor: FBProfileFormulasViewControllerOutput
{
}

extension FBProfileFormulasPresenter: FBProfileFormulasInteractorOutput
{
}

class FBProfileFormulasConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = FBProfileFormulasConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: FBProfileFormulasViewController)
  {
    let router = FBProfileFormulasRouter()
    router.viewController = viewController
    
    let presenter = FBProfileFormulasPresenter()
    presenter.output = viewController
    
    let interactor = FBProfileFormulasInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
