//
//  FBProfileFormulasPresenter.swift
//  FormulaBuilderCS
//
//  Created by a on 2/19/17.
//  Copyright (c) 2017 orgname. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol FBProfileFormulasPresenterInput
{
    func presentFetchedFormulas(response: FBFormulaSearch.FetchFormulas.Response)
}

protocol FBProfileFormulasPresenterOutput: class
{
    func displayFetchedFormulas(viewModel: FBProfileFormulas.FetchFormulas.ViewModel)
}

class FBProfileFormulasPresenter: FBProfileFormulasPresenterInput
{
    weak var output: FBProfileFormulasPresenterOutput!
  
  // MARK: - Presentation logic
  
    func presentFetchedFormulas(response: FBFormulaSearch.FetchFormulas.Response) {
        var displayedFormulas = [DisplayedFormula]()
        
        for formula in response.formulas {
            let displayFormula = DisplayedFormula(with: formula)
            displayedFormulas.append(displayFormula)
        }
        
        let viewModel = FBProfileFormulas.FetchFormulas.ViewModel(displayedFormulas: displayedFormulas)
        output.displayFetchedFormulas(viewModel: viewModel)
    }
}
